services:
  chibisafe:
    image: chibisafe/chibisafe:latest
    container_name: chibisafe
    environment:
      - BASE_API_URL=http://chibisafe_server:8000
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - homelab-net

  chibisafe_server:
    image: chibisafe/chibisafe-server:latest
    container_name: chibisafe-server
    volumes:
      - ./database:/app/database:rw
      - ./uploads:/app/uploads:rw
      - ./logs:/app/logs:rw
    expose:
      - 8000
    restart: unless-stopped
    networks:
      - homelab-net

