[Interface]
Address = 10.2.0.2
PrivateKey = eChM5MQPnZfnO5bVgFYRSfsALHjtV1213n0ilVm/1EA=
ListenPort = 51820
DNS = 10.2.0.1

[Peer]
PublicKey = 6De7f4rHGe/JUIlA/ITYSTtwgNsVKlnGVKmKyTidZWs=
PresharedKey = GZACIWq7iAslNUuwM/Xkv493MyX8n5UrhMrOILXpN8w=
Endpoint = nebulea.dev:51820
AllowedIPs = 0.0.0.0/0, ::/0
