services:
  dozzle:
    image: amir20/dozzle:latest
    ports:
      - "8080:8080"
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/data
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
    networks:
      - homelab-net
